# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
    -   id: trailing-whitespace
        exclude: ^APIs/mesh2points/data/
    -   id: end-of-file-fixer
    -   id: check-added-large-files

-   repo: https://github.com/ambv/black
    rev: stable
    hooks:
    -   id: black
        language_version: python3.9.7
        exclude: ^(doc|monitoring|scripts|tool|test)/|APIs/mesh2points/data/ModelNet10/

-   repo: https://github.com/PyCQA/pylint
    rev: v2.14.0
    hooks:
    -   id: pylint
        exclude: ^APIs/mesh2points/data/

-   repo: https://github.com/pycqa/isort
    rev: ''
    hooks:
    -   id: isort
        exclude: ^APIs/mesh2points/data/

exclude: ^(APIs/mesh2points/data/ModelNet10/README\.txt)|^README\.md$
